# Generated by Django 5.1.5 on 2025-02-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
